import { ModelInfo } from "@nova/shared";

export const FALLBACK_OPENROUTER_SNAPSHOT: ModelInfo[] = [
  {
    id: "meta-llama/llama-3.3-70b-instruct:free",
    name: "Meta: Llama 3.3 70B Instruct (free)",
    provider: "openrouter",
    providerName: "OpenRouter (Meta)",
    contextWindow: 131072,
    supportsTools: true,
    supportsStreaming: true,
    isLocal: false,
    isFree: true,
    description:
      "Meta's open 70B model running free with strong instruction following and tool calling.",
    costPer1kInput: 0,
    costPer1kOutput: 0,
    recommendedFor: "General agent workflows & free exploration",
  },
  {
    id: "deepseek/deepseek-r1:free",
    name: "DeepSeek: R1 (free)",
    provider: "openrouter",
    providerName: "OpenRouter (DeepSeek)",
    contextWindow: 65536,
    supportsTools: false,
    supportsStreaming: true,
    isLocal: false,
    isFree: true,
    description:
      "DeepSeek's flagship open-weights reasoning model with chain-of-thought problem solving.",
    costPer1kInput: 0,
    costPer1kOutput: 0,
    recommendedFor: "Deep reasoning, math, and code generation",
  },
  {
    id: "google/gemini-2.0-flash-exp:free",
    name: "Google: Gemini 2.0 Flash Experimental (free)",
    provider: "openrouter",
    providerName: "OpenRouter (Google)",
    contextWindow: 1048576,
    supportsTools: true,
    supportsStreaming: true,
    isLocal: false,
    isFree: true,
    description:
      "Google next-gen high-throughput multimodal intelligence with 1M context window.",
    costPer1kInput: 0,
    costPer1kOutput: 0,
    recommendedFor: "High speed tasks, massive context analysis",
  },
  {
    id: "qwen/qwen-2.5-coder-32b-instruct:free",
    name: "Qwen: Qwen 2.5 Coder 32B Instruct (free)",
    provider: "openrouter",
    providerName: "OpenRouter (Qwen)",
    contextWindow: 32768,
    supportsTools: true,
    supportsStreaming: true,
    isLocal: false,
    isFree: true,
    description:
      "Alibaba's dedicated code generation model with strong syntax and reasoning capabilities.",
    costPer1kInput: 0,
    costPer1kOutput: 0,
    recommendedFor: "Software development and code automation",
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Anthropic: Claude 3.5 Sonnet",
    provider: "openrouter",
    providerName: "OpenRouter (Anthropic)",
    contextWindow: 200000,
    supportsTools: true,
    supportsStreaming: true,
    isLocal: false,
    isFree: false,
    description:
      "State-of-the-art coding and agentic reasoning model with nuanced tool comprehension.",
    costPer1kInput: 0.003,
    costPer1kOutput: 0.015,
    recommendedFor:
      "Complex multi-step tool workflows & software development",
  },
  {
    id: "openai/gpt-4o",
    name: "OpenAI: GPT-4o",
    provider: "openrouter",
    providerName: "OpenRouter (OpenAI)",
    contextWindow: 128000,
    supportsTools: true,
    supportsStreaming: true,
    isLocal: false,
    isFree: false,
    description:
      "OpenAI's flagship multimodal intelligence with high tool accuracy.",
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
    recommendedFor: "Complex reasoning and fast tool execution",
  },
  {
    id: "openai/gpt-4o-mini",
    name: "OpenAI: GPT-4o Mini",
    provider: "openrouter",
    providerName: "OpenRouter (OpenAI)",
    contextWindow: 128000,
    supportsTools: true,
    supportsStreaming: true,
    isLocal: false,
    isFree: false,
    description:
      "Fast, cost-effective model for high volume agent workflows.",
    costPer1kInput: 0.00015,
    costPer1kOutput: 0.0006,
    recommendedFor: "Affordable multi-step agent actions",
  },
];
